### ISSUE TITLE
scalajs support

### ISSUE THREAD

**Issue by antonkulaga** [softwaremill/odelay#12]
Absence of scalajs support in odelay core blocks me from adding scalajs support to retry library ( https://github.com/softprops/retry ).

**Comment by softprops** [comment]
have you tried implementing an [Timer](https://github.com/softprops/odelay#timers)? You can find some examples in the third party modules like netty and twitter.

**Comment by aappddeevv** [comment]
We would need to breakout core to core and pure-core where pure-core does not have a dependency on anything. core could have a dependency on pure-core. Then we could write a scalajs backend. 

Would you take a PR that uses this approach?

**Comment by softprops** [comment]
I'd be happy to take prs!

**Comment by aappddeevv** [comment]
Created a fork with scalajs support that passes tests (modified) and I think preserves the other sub-projects. https://github.com/aappddeevv/odelay. I'll looking into a PR.

**Comment by aappddeevv** [comment]
Can you push these to your bintray? I need to pick them through the standard sbt resolution process so I can ensure the travis build for retry works.

**Comment by softprops** [comment]
done

**Comment by aappddeevv** [comment]
Thanks. Have a small issue on the pull that I'm providing another pull with the same library version number. Apparently in retry, there was use of implicitly[Timer] and that was not in the odelay tests. I'll create the new pull request. Added a test for the implicit.
